# Generated by Django 3.1.3 on 2022-07-27 05:00

import app.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='описание')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('serial_number', models.CharField(max_length=100, verbose_name='номер на счетчике')),
                ('state', models.BooleanField(default=False, verbose_name='вкл/выкл')),
                ('register_time', models.DateTimeField(auto_now=True, verbose_name='время регистрации')),
                ('initial_reading_time', models.DateTimeField(null=True, verbose_name='время начального показания')),
                ('initial_value', models.FloatField(default=0.0, verbose_name='время первого показания')),
                ('measurement_unit', models.CharField(max_length=100, verbose_name='единица измерения')),
            ],
            options={
                'ordering': ('uuid',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('geo', geoposition.fields.GeopositionField(max_length=42)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('address', models.TextField(max_length=100)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='app.customer', verbose_name='владелец')),
            ],
            options={
                'ordering': ('uuid',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('state', models.BooleanField(default=False, verbose_name='вкл/выкл')),
                ('last_reading_time', models.DateTimeField(null=True, verbose_name='время последнего показания')),
                ('activation_time', models.DateTimeField(null=True, verbose_name='время активации')),
                ('description', models.TextField(verbose_name='описание')),
                ('type', models.CharField(choices=[('TYPE1', 'TYPE1'), ('TYPE2', 'TYPE2')], default=app.utils.DeviceType['TYPE1'], max_length=50, verbose_name='тип устройства')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='app.customer', verbose_name='владелец')),
            ],
            options={
                'ordering': ('uuid',),
                'abstract': False,
            },
        ),
    ]
